project:
  type: website
  output-dir: docs
  execute-dir: project


website:
  title: "baseball_team_site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

