project:
  type: website
  output-dir: docs
  execute-dir: project


website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 2025.qmd
        text: "2025"
      - href: 2026.qmd
        text: "2026"
format:
  html:
    theme:
      - brand
      - minty
    css: styles.css
    toc: true

editor: visual

